stages:
  - verify

default:
  image: ghcr.io/cirruslabs/flutter:3.47.4

cache:
  key: pub
  paths:
    - .pub-cache/

variables:
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

analyze:
  stage: verify
  script:
    - flutter pub get
    - dart analyze lib/
